### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by DanielGoehler**
To work with the BaseApp in VScode, it would be nice to exclude some files from Git.

### CODE REVIEW

**Comment by StefanMaron** [comment]
Could you explain what do you mean with working with the base app? Do you work and change code directly within this repo?

**Comment by DanielGoehler** [comment]
My goal is not to change or publish the BaseApp. What I do with the BaseApp:
- Look up events in Business Central
- Temporarily create the publisher event for the event request on https://github.com/Microsoft/ALAppExtensions
- ...

To access all the references, I added a launch.json for the Microsoft_System Application_*.app and Microsoft_System_*.app icons. I also adjusted the settings.json so that I don't need 32 GB of RAM to open the BaseApp, and added the "al.assemblyProbingPaths" so that the BaseApp compiles and I ensure that my temporary changes for event request can be compiled.

This .gitignore would help me not have the launch.json, Microsoft_System Application_*.app and Microsoft_System_*.apps. rad.json, settings.json and the cache files as pending git changes and I can easily revert all changes.

**Comment by StefanMaron** [comment]
Got it 👍 would you mind to also add the settings adjustments you made? I am sure this would be helpful to others as well

**Comment by DanielGoehler** [comment]
I found that this is not necessary when using the base-app.code-workspace. I have added al.backgroundCodeAnalysis = false.

**Comment by StefanMaron** [comment]
Updated in all commits across all branches

**Pull request closed without merging**
